name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Swift command line
      run: swift build -v
#    - name: Run tests
#      run: swift test -v
