name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Swift command line
      run: swift build -v
    - name: Build with Xcodebuild
      run: xcodebuild
      
    - name: Run tests
      run: swift test -v
